#This configuration file was written by: org.eclipse.oomph.p2.internal.core.AgentImpl
#Fri Jul 10 10:26:27 IST 2026
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.40.0.20260604-0652
eclipse.p2.data.area=file\:/C\:/Users/somva/.p2/
eclipse.p2.profile=C__Users_somva_eclipse_java-2026-06_eclipse
eclipse.product=org.eclipse.epp.package.java.product
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.5.700.v20251111-1031.jar@1\:start
osgi.bundles.defaultStartLevel=4
osgi.framework=file\:/C\:/Users/somva/.p2/pool/plugins/org.eclipse.osgi_3.24.200.v20260515-1403.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.3.0.v20251022-1724.jar
osgi.instance.area.default=@user.home/workspace
osgi.splashPath=file\:/C\:/Users/somva/.p2/pool/plugins/org.eclipse.epp.package.common_4.40.0.20260604-0652
